name: 'NPM Build and Publish'
description: 'Build and publish an NPM package with versioning and dependency updates.'
inputs:
  package-version:
    description: 'Package version to set in package.json'
    required: false
  config-file:
    description: 'Path to the configuration file'
    required: false
  run-tests:
    description: 'Whether to run tests before publishing'
    required: false
    default: 'false'
  publish-tag:
    description: 'NPM publish tag (e.g., latest, beta)'
    required: false
    default: 'latest'

runs:
  using: 'node20'
  main: 'src/index.js'
