name: 'NPM Build and Publish'
description: 'Build and publish an NPM package with versioning and dependency updates.'
inputs:
  version:
    description: 'New version (e.g., 1.0.1)'
    required: true

runs:
  using: 'node20'
  main: 'index.js'