name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        default: "1.0.1"
        description: "New version (e.g., 1.0.1)"
        required: true
      node-version:
        default: "20"
        description: "Node.js version (e.g., 20)"
        required: true
      registry-url:
        default: "https://npm.pkg.github.com"
        description: "NPM registry URL"
        required: false
      update-nc-dependency:
        type: boolean
        default: false
        description: "Update dependencies"
        required: false

jobs:
  publish:
    uses:  nookyo/workflow-hub/.github/workflows/npm-publish.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      node-version: ${{ github.event.inputs.node-version }}
      registry-url: ${{ github.event.inputs.registry-url }}
      update-nc-dependency: ${{ github.event.inputs.update-nc-dependency }}