name: NPM Action

on:
  workflow_dispatch:
    inputs:
      version:
        default: ""
        description: "New version (e.g., 1.0.1)"
# Remake it into a normal action game with version calc, bump and all the crap
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
          scope: '@nookyo'

      - name: Authenticate with GitHub Packages
        run: |
          echo "@nookyo:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc

      - name: My action use
        uses: ./actions/npm-manager
        with:
          version: ${{ inputs.version }}
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}




