name: NPM Action

on:
  workflow_dispatch:
    inputs:
      version:
        default: "1.0.1"
        description: "New version (e.g., 1.0.1)"
        required: true
# Remake it into a normal action game with version calc, bump and all the crap
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: My action use
        uses: ./actions/npm-manager



